# -*- mode: shell-script -*-

### git aliases
alias gstat='git status'

alias serve='python -m http.server'

### Gradle related aliases
alias gr="./gradlew run"

# Alias for various VSCodium Profiles
alias platformio='codium --profile "Embeded"'
alias vscode='codium --profile "Default"'
alias scriptside='codium --profile "ScriptsIDE"'

## Aliases for zellij layouts
alias spark='zellij --layout spark'
alias scripts='zellij --layout scripts'
alias fit-customer-app='zellij --layout fit-customer-app'
alias in-bay='zellij --layout in-bay-orchestrator'
alias dotfiles='zellij --layout dotfiles'
alias utilites='zellij --layout utilites'
alias golfbot='zellij --layout golfbot'
alias timerapp='zellij --layout timerapp'
alias merlin='zellij --layout merlin'
alias models='zellij --layout models'

## Docker Compose aliases
alias dcu-db='docker compose -f ~/workarea/getforj/utils/docker-services/docker-compose.yml up -d'


### git aliases
alias gstat='git status'
alias gpush='git push'