# -*- mode: shell-script -*-

### git aliases
alias gstat='git status'

alias serve='python -m http.server'

### Gradle related aliases
alias gr="./gradlew run"


# Alias for various VS Code Profiles
alias platformio='code --profile "Embeded"'
alias vscode='code --profile "Default"'
alias scriptside='code --profile "ScriptsIDE"'

## Terminator related aliases
## I have moved to zellij. Comment and leaving in file for historic reasons.
# alias dev-teebox='terminator -l TeeBox'
# alias dev-orch='terminator -l OrchDev'
# alias dev-spark='terminator -l SparkDev'

